name: Build Windows Executable

on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
      - '!*-patch-*'
  pull_request:
  workflow_dispatch:

jobs:
  build-windows-executable:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version-file: .github/python-version.txt

      - run: pip install .[dev]  # pyinstaller 5.9 does not like pyproject.toml + editable installs.
      - run: python -u release/build.py installbuilder-installer msix-installer
        env:
          CI_BUILD_KEY:  'ylgPSW9nDBqswK6wdyu--oXDLT6H1rrZm-uCJAC6Oz8=' # ${{ secrets.CI_BUILD_KEY || 'mocked_key_for_testing' }}

      - uses: actions/upload-artifact@v4
        with:
          name: binaries.windows-installer
          path: release/dist 
